#!/usr/bin/env node

/**
 *
 * This code will ensure that before every commit in your client repository, your branch name and commit message adheres to a certain contract.
 * In this example, branch names must be like 'B2B-3333' and commit messages must start like some issue code, like B2B-3333.
 *
 * 'B2B' is an example. I made this example with Jira in mind, since Jira issue codes have this structure -as far as I know-, but is pretty easy to change it to any other issue id like #100 or $-AP-120, or whatever.
 *
 * In order for this to work, you should go to .git/hooks in any git client repository and create a prepare-commit-msg file (or modify the provided by default, prepare-commit-msg.sample) with
 * this contents.
 *
 * You need an await/async compliant version of node installed in your machine.
 *
 * Don't forget to make your file executable!
 */

const fs = require('fs');
const childProcess = require('child_process');
const util = require('util');

const BRANCH_CONTRACT = /\b[A-Z][A-Z0-9_]+-[1-9][0-9]*/;
const TIMEOUT_THRESHOLD = 3000;

const childProcessExec = childProcess.exec;

const exec = util.promisify(childProcessExec);

checkCommitMessage();
hookCleanup();

async function checkCommitMessage() {
	// читаем файл, содержащий сообщение к комиту
	const message = fs.readFileSync(process.argv[2], 'utf8').trim();

	let branchName = '';

	// получаем название ветки
	try {
		branchName = await getCurrentBranch();
	} catch (e) {
		handleGitBranchCommandError(e);
	}

	// если название ветки соответствует нашему регулярному выражению
	if (BRANCH_CONTRACT.test(branchName)) {
		// если сообщение не содержит название ветки, то записываем в файл, содержащий сообщение к коммиту
		if (!message.includes(branchName)) {
			fs.writeFileSync(process.argv[2], `${branchName}: ${message}`, 'utf-8');
		}
	}

	process.exit(0);
}

async function getCurrentBranch() {
	const branchesOutput = await exec('git branch');

	if (branchesOutput.stderr) {
		throw new Error(stderr);
	}

	const branches = branchesOutput.stdout;

	return branches
		.split('\n')
		.find(b => b.trim().charAt(0) === '*')
		.trim()
		.substring(2);
}

function handleGitBranchCommandError(e) {
	console.log(
		'something bad happened when trying to read the repository branches using the "git branch" command'
	);
	console.log(
		"this is script is intended to be run as a git hook inside a git repository. Are you sure you're calling it properly?"
	);
	console.log('the error provided by the "git branch" invocation was the following:');
	console.log(e.getMessage());
	console.log('----');
	console.log('Your commit will be rejected. This script will terminate.');

	process.exit(1);
}

function hookCleanup() {
	setTimeout(() => {
		console.log(
			'This is a timeout message from your commit-msg git hook. If you see this, something bad happened in your pre-commit hook, and it absolutely did not work as expected.'
		);
		console.log(
			' Your commit will be rejected. Please read any previous error message related to your commit message, and/or check the commit-msg git hook script.'
		);
		console.log(
			' You can find more info in this link: https://git-scm.com/book/uz/v2/Customizing-Git-An-Example-Git-Enforced-Policy'
		);
		process.exit(1);
	}, TIMEOUT_THRESHOLD);
}
